travis:
  secure:
    BINSTAR_TOKEN: EtWVB5OuY7NiFc7Olai3dDhS52l0sT5xlQLw6Mle8yBcI+86h/9WG3sQ7hVppc1sxy+YMTi/eJIB9CrbccTaSdysrBfSyKFM02mvMVTj5vvP2qYhKKYVFSx1RJrFYC254yvWW/GMKa9lS86MyH3OxXBQNzSQEDC5dcB4m2PFdm62UZEJRS+sW9HCW6Z+6DHMoknYtrNiY18KZk4wqnYRyMX9+LTEr+PEvGhPbtmTNGQUPGPNT2aFl05RswYpw3xBiOZOKSYrNvFQxS2CmBcCm529Gh2Zbga/zvEN+wn4Tq3880Buo4hY8wtETVFnCLlIS0oax/kJsplMR3b7bQvIz53YFlnpEgpbV7zh4BKa1Oc1bqnP+yTMiPbZF2lIoI080f5QCRNLtnpnWUAYVyUrgH44qNVRrPXbpE0k6ja1AKpOKYmYKphcpbBvkEdXTdzFE81vpaf+1XbKvuUb5VE3E+MahKMWo1SXcaloLWfT/xd+1X/7Gmwvn7Z0WtgZyY9d6fpRMilVlnXOHru54wP08hZELxHmTw1eKOsavMLR9pU+6qkf/kYUKmhk9aLpHXuDFMbw+x49wQI95Jmv4xHbqAcQWydWTHvM10cbh62XxWcaljIYkq8EvY+HVHlNMVRzCIyfFn5sq9hJ5ter+a3kC4MAss9TdFswOxTmTCcn+9g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
